### ISSUE TITLE
Could you please provide the processed training and test data?

### ISSUE THREAD

**Issue by yuanzhen2020** [chengzhag/DeepPanoContext#5]
Could you please provide the processed training and test data(like Total3DUnderstanding) so that we can download it directly?

**Comment by chengzhag** [comment]
Hi, @yuanzhen2020,

Let's discuss via email: chengzhag@std.uestc.edu.cn

**Comment by chengzhag** [comment]
The dataset link has been updated in c21b8435eb856cd8df6138181d06b27df1b2c978, after consulting the auther (https://github.com/StanfordVL/iGibson/issues/222).
