### ISSUE TITLE
Model weights for LIEN, LDIF and BEN modules

### ISSUE THREAD

**Issue by davisj147** [chengzhag/DeepPanoContext#6]
The provided links in the readme contain model weights for the detector, layout estimation, and relation_scene_gcn modules, as well as the total3D weights.

Would it be possible to also provide the weights for the LIEN, LDIF and BEN modules?

Many thanks!

**Comment by chengzhag** [comment]
Hi, @davisj147,

Thanks for your interest in our paper!

If you can run the demo to produce the reconstruction without a problem, all the weights should be in there. The name of the folder 'relation_scene_gcn' indicates only the core module we proposed in our paper, but should also include the weights of LIEN, LDIF and BEN.
