### ISSUE TITLE
how to show 3D interactive result

### ISSUE THREAD

**Issue by arctanbell** [chengzhag/DeepPanoContext#7]
Well done for the excellent work, I got the predicted result after following the demo instructions, and I wander to get the 3D interactive result as https://chengzhag.github.io/publication/dpc/ shows, which tool can I use plz

**Comment by chengzhag** [comment]
Hi, @arctanbell,

We use [model-viewer](https://modelviewer.dev) to show the 3D interactive results.

**Comment by arctanbell** [comment]
thanks for your response
